Document: tapecrypt
Title: Debian tapecrypt Manual
Author: <insert document author here>
Abstract: This manual describes what tapecrypt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tapecrypt/tapecrypt.sgml.gz

Format: postscript
Files: /usr/share/doc/tapecrypt/tapecrypt.ps.gz

Format: text
Files: /usr/share/doc/tapecrypt/tapecrypt.text.gz

Format: HTML
Index: /usr/share/doc/tapecrypt/html/index.html
Files: /usr/share/doc/tapecrypt/html/*.html
